baseURL: "https://blog.internetz.me/"
languageCode: "en-us"
title: "shit i like"
theme: "toha"
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false
# Enable Google Analytics
#googleAnalytics: UA-XXXXXXXXX-X

# Enable Disqus forum
disqusShortname: does-not-exist

# Enable global emoji support
enableEmoji: true

# Custom parameters
params:
  # Copyright Notice
  copyright: Â© 2020 Copyright.

  # Meta description for your site.  This will help the search engines to find your site.
  description: Portfolio and personal blog of loeken.

  # background image of the landing page
  background: "images/background.jpg"

  # Provide logos for your site. The inverted logo will be used in the initial
  # transparent navbar and the main logo will be used in the non-transparent navbar.
  # It will be default to the theme logos if not provided.
  logo:
    main: /assets/images/main-logo.png
    inverted: /assets/images/inverted-logo.png

  # GitHub repo URL of your site
  gitRepo: https://github.com/loeken/blog

  # specify whether you want to write blog post or not
  enableBlogPost: true

  # specify whether you want to show Table of Contents in reading page
  enableTOC: true

  # specify the list of custom menus that you want to show in the top navbar.
  # they will be separated by a divider from the main menus.
#  customMenus:
#  - name: Notes
#    url: https://hossainnotes.netlify.app/docs/example/

  # Provide newsletter configuration. This feature hasn't been implemented yet.
  # Currently, you can just hide it from the footer.
  newsletter:
    enable: false

  # some information about you
  author:
    name: "loeken"
    nickname: "loeken"
    image: "images/avatar.png"
    # give your some contact information. they will be used in the footer
    contactInfo:
      email: "loeken@internetz.me"
    # a summary of what you do
    summary:
    - I am a Devops Engineer
    - I love to code
    - I run a small tech youtube channel
    - I love to work with kuberentesd
    - Talk nerdy to me!
